---
$schema: "file://../cache/schemas/tasks.json"

inheritedBy:
  tags: npm-publish

tasks:
  npm-publish:
    type: run
    deps:
      - "^:npm-publish"
      - "~:build"
    command: "${MOON_WORKSPACE_ROOT}/pkgs/tools/deployment/npm-publish"
    options:
      cache: false
      runInCI: true
